### ISSUE TITLE
assets:precompile step fails when port 5432 not exposed during build

### ISSUE THREAD

**Issue by hxegon** [heroku/docker-ruby#15]
The assets:precompile step fails on my machine, and I've confirmed this on a co-workers machine. It's the setup from the heroku docker init, + a simple database.yml:

My dockerfile `FROM heroku/ruby`

docker-compose.yml:

``` yml
web:
  build: .
  command: 'bash -c ''bundle exec puma -C config/puma.rb'''
  working_dir: /app/user
  environment:
    PORT: 8080
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
  ports:
    - '8080:8080'
  links:
    - herokuPostgresql
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8080
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
  ports:
    - '8080:8080'
  links:
    - herokuPostgresql
  volumes:
    - '.:/app/user'
herokuPostgresql:
  image: postgres
```

config/database.yml:

``` yml
# Copied from https://docs.docker.com/compose/rails/#connect-the-database
development: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password:
  host: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production
```

The error I get:

```
rake aborted!
PG::ConnectionBad: could not connect to server: No such file or directory
                Is the server running locally and accepting
                connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

I've worked around this by putting `ONBUILD EXPOSE 5432` into a copied `Dockerfile` from this repo.
